'use strict';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusNames={validating:'Checking courses',planning:'Checking courses',ready:'Ready for review',queued:'Queued',running:'Processing',submitted:'Deployment submitted',submittedWithErrors:'Some deployments need attention',outcomeUnknown:'Check deployment outcome',activated:'Replicas active',activationWithErrors:'Activation needs attention',completed:'Dates verified',completedWithErrors:'Completed with issues',failed:'Needs attention',interrupted:'Processing interrupted',cancelled:'Cancelled',valid:'Valid',invalid:'Invalid',pending:'Pending',duplicate:'Duplicate',updated:'Updated',unchanged:'Unchanged',skipped:'Skipped',uncertain:'Check outcome'};
function badge(status){const tone=['completed','activated','updated','valid','unchanged'].includes(status)?'success':['failed','invalid','interrupted','uncertain','outcomeUnknown','activationWithErrors','completedWithErrors','submittedWithErrors'].includes(status)?'warning':'neutral';return `<span class="badge ${tone}">${escape(statusNames[status]||status||'Pending')}</span>`;}
function steps(items,current=0){return `<ol class="steps" aria-label="Workflow progress">${items.map((label,i)=>`<li class="${i===current?'current':i<current?'done':''}" ${i===current?'aria-current="step"':''}><span>${i+1}</span>${escape(label)}</li>`).join('')}</ol>`;}
function table(headings,rows,empty='No results yet.'){return rows.length?`<div class="table-scroll" tabindex="0" role="region" aria-label="${escape(headings.join(', '))}"><table><thead><tr>${headings.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="empty-state">${escape(empty)}</div>`;}
function upload(id,headers,description){return `<div class="upload-box"><span class="eyebrow">Course list</span><h3>Upload your CSV</h3><p>${escape(description)}</p><label class="file-label" for="${id}-file">Choose a CSV file</label><input id="${id}-file" type="file" ${id==='bulk'?'required':''} accept=".csv,text/csv" data-csv-target="${id}-csv" data-max-bytes="${id==='bulk'?5242880:16384}"><p id="${id}-message" class="muted" role="status">UTF-8 CSV · up to ${id==='bulk'?'10,000 rows · 5 MB':'100 rows · 16 KB'}</p><a download="${id}-template.csv" href="data:text/csv;charset=utf-8,${encodeURIComponent(headers+'\r\n')}">Download CSV template</a></div>${id==='bulk'?`<textarea id="${id}-csv" name="csv" hidden></textarea>`:`<details class="csv-editor"><summary>Paste or review CSV contents</summary><label for="${id}-csv">CSV contents</label><textarea id="${id}-csv" name="csv" rows="5" required placeholder="${escape(headers)}" aria-describedby="${id}-message"></textarea></details>`}`;}
function notice(message,type='default'){return `<d2l-alert type="${type}">${escape(message)}</d2l-alert>`;}
function workspace({dates,replication,history,tools,selected='dates'}){const panes=[['dates','Activity Dates',dates],['replication','Source Replication',replication],['history','Job History',history]];return `<d2l-tabs text="Course operations">${panes.map(([id,label,content])=>`<d2l-tab slot="tabs" id="tab-${id}" text="${label}" ${selected===id?'selected':''}></d2l-tab><d2l-tab-panel slot="panels" labelled-by="tab-${id}">${content}</d2l-tab-panel>`).join('')}</d2l-tabs><details class="developer-tools"><summary>Development tools</summary>${tools}</details>`;}
function page(content,{ltik='',section='dates'}={}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Brightspace Source Course Operations</title><link rel="stylesheet" href="/assets/app.css"><script type="module" src="/assets/app.js"></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="app-header"><div class="brand"><span class="brand-mark" aria-hidden="true">B</span><div><strong>Brightspace Source Course Operations</strong><span>Bulk Activity Date Manager and Bulk Source Course Deployer</span></div></div>${ltik?`<form method="post" action="/workspace" class="inline-form"><input type="hidden" name="ltik" value="${escape(ltik)}"><input type="hidden" name="section" value="${escape(section)}"><button>Workspace</button></form>`:''}</header><main id="main" tabindex="-1">${content}</main><footer>Activity dates &amp; Source Course replication <span>Times shown in Brasília · UTC−03:00</span></footer></body></html>`;}
module.exports={escape,badge,steps,table,upload,notice,workspace,page,statusNames};
