'use strict';
const {escape,badge,steps,table,upload,notice}=require('../ui/page');
const {DEFAULT_ZONE,ZONES}=require('./timeZone');
const date=(value,timeZone=DEFAULT_ZONE)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone,dateStyle:'short',timeStyle:'medium'}).format(new Date(value)):'No date';
const names={assignment:'Assignment',quiz:'Quiz',discussionTopic:'Discussion Topic'};
function createDateView({writeEnabled}){return {
 form(res,{controls,button}){const values=res.locals?.dateForm||{};return `<section id="date-management">${steps(['Upload Source Courses','Review Updates','Apply and Update'])}<form method="post" action="/bulk/preview" id="bulk-input">${controls(res,'preview')}<div class="form-grid"><div class="panel">${upload('bulk','OrgUnitId,OrgUnitCode','Provide one source course ID or code per row. Duplicate source courses are processed once.')}</div><div class="panel"><span class="eyebrow">Schedule</span><h3>Choose the new dates</h3><label class="field">Time zone<select name="timeZone" required style="display:block;width:100%;margin-top:7px">${ZONES.map(zone=>`<option value="${escape(zone)}" ${zone===(values.timeZone||DEFAULT_ZONE)?'selected':''}>${escape(zone===DEFAULT_ZONE?'Brasília — America/Sao_Paulo':zone.replaceAll('_',' '))}</option>`).join('')}</select></label>${['start','due','end'].map(k=>`<label class="field">${k[0].toUpperCase()+k.slice(1)} date and time<input type="datetime-local" name="${k}" step="1" value="${escape(values[k]||'')}" required></label>`).join('')}<p class="muted">Start must be before Due. End must be on or after Due.</p></div></div><div class="action-bar date-upload-actions"><button class="primary">2. Review Updates</button></div></form></section>`;},
 render(res,job,{button,now,page=1}){
 const review=job.status==='ready';
 const success=job.status==='completed'&&job.tasks.length>0&&job.tasks.every(t=>['updated','unchanged'].includes(t.result?.status));
 const checking=['validating','planning'].includes(job.status);
 const updating=['queued','running'].includes(job.status);
 const simplified=review||success||checking||updating;
 const updated=job.tasks.filter(t=>t.result?.status==='updated').length;
 const unchanged=job.tasks.filter(t=>t.result?.status==='unchanged').length;
 const timeZone=job.timeZone||DEFAULT_ZONE;
 const pageSize=100,pages=Math.max(1,Math.ceil(Math.max(job.rows.length,job.courses.length,job.tasks.length)/pageSize));
 page=Math.min(pages,Math.max(1,Number.isSafeInteger(page)?page:1));
 const slice=items=>items.slice((page-1)*pageSize,page*pageSize);
 const navigation=`<div class="toolbar"><span>Page ${page} of ${pages} · up to 100 records per table</span>${page>1?button(res,'status',job._id,'Previous',`data-page="${page-1}"`):''}${page<pages?button(res,'status',job._id,'Next',`data-page="${page+1}"`):''}</div>`;
 const active=['validating','planning','queued','running'].includes(job.status),permitted=job.tasks.every(t=>writeEnabled(t.activity.type));
 const stage=['validating','planning'].includes(job.status)?0:job.status==='ready'?1:2;
 const issues=job.tasks.filter(t=>['failed','skipped'].includes(t.result?.status)).length;
 return `${checking?'<div data-date-checking hidden></div>':''}${updating?'<div data-date-updating hidden></div>':''}${review?'<div data-date-review hidden></div>':''}${success?'<div data-date-success hidden></div>':''}${simplified?'':`<div class="section-heading"><div><span class="eyebrow">Activity dates</span><h1>Review your date updates</h1></div>${badge(job.status)}</div>`}${steps(['Upload Source Courses','Review Updates','Apply and Update'],stage)}<div class="metrics"><div><strong>${job.courses.length}</strong><span>Courses</span></div><div><strong>${job.tasks.length}</strong><span>Activities</span></div><div><strong>${issues}</strong><span>Need attention</span></div></div>${job.message?notice(job.message,'warning'):''}${checking&&job.progress?`<p role="status">${escape(job.progress.phase)}: ${job.progress.processed.toLocaleString()} / ${job.progress.total.toLocaleString()}${job.progress.activities!==undefined?` · ${job.progress.activities.toLocaleString()} activities found`:''}</p>`:''}${success?`<section class="confirmation success-confirmation" role="status"><h2>✓ Activity Dates Updated</h2><p>${updated?`Updated dates for <strong>${updated} ${updated===1?'activity':'activities'}</strong>. `:''}${unchanged?`<strong>${unchanged} ${unchanged===1?'activity already had':'activities already had'}</strong> the requested dates. `:''}All <strong>${job.tasks.length} ${job.tasks.length===1?'activity':'activities'}</strong> across <strong>${job.courses.length} source ${job.courses.length===1?'course':'courses'}</strong> now have the requested dates, updated in Brightspace.</p></section>`:''}<section class="panel"><h2>${success?'Updated Dates':'Requested Dates'} <small>${escape(timeZone)}</small></h2><div class="date-summary">${['start','due','end'].map(k=>`<div><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${escape(date(job.dates[k],timeZone))}</strong></div>`).join('')}</div></section>
 ${job.status==='ready'&&job.expiresAt>now()&&permitted?`<section class="confirmation"><h2>Ready to apply</h2><p>This will update all <strong>${job.tasks.length} ${job.tasks.length===1?'activity':'activities'}</strong> in <strong>${job.courses.length} source ${job.courses.length===1?'course':'courses'}</strong>. Confirm the requested dates above before continuing.</p><div class="confirmation-actions">${button(res,'apply',job._id,'3. Apply & Update')}</div></section>`:''}
 ${job.status==='ready'&&!permitted?notice('Apply is unavailable. Configure the required write scopes for every activity type in this plan.','warning'):''}${job.status==='ready'&&job.expiresAt<=now()?notice('This preview expired. Return to Workspace and create a new preview.','warning'):''}
 ${active?`<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>${updating?'Updating your Source Courses':'Checking your Source Courses'}</strong><p>Results refresh every 10 seconds. You can close this page and return through Job history.</p></div></div>`:''}
 <div class="toolbar">${button(res,'status',job._id,'Refresh status',`id="job-refresh" data-page="${page}"`)}${button(res,'report',job._id,'Download CSV report')}${simplified?'':button(res,'history','','My recent jobs')}${['validating','ready','queued'].includes(job.status)?button(res,'cancel',job._id,'Cancel this job'):''}</div>
 ${simplified?'':`${navigation}<details class="panel" ${job.rows.some(r=>r.status==='invalid')?'open':''}><summary>CSV validation · ${job.rows.length} rows</summary>${table(['Row','ID / code','Resolved ID','Status','Details'],slice(job.rows).map(r=>[escape(r.row),escape(r.orgUnitId||r.orgUnitCode),escape(r.resolvedId),badge(r.status),escape(r.message||'—')]))}</details>
 <details class="panel" ${job.courses.some(c=>c.status==='invalid')?'open':''}><summary>Course validation · ${job.courses.length} courses</summary>${table(['Course','Name','Status','Details'],slice(job.courses).map(c=>[escape(c.orgUnitId),escape(c.name||'—'),badge(c.status),escape(c.message||'—')]))}</details>
 <section class="panel"><h2>Activities <small>Current / verified dates · ${escape(timeZone)}</small></h2>${table(['Course','Activity','Status','Start','Due','End','Details'],slice(job.tasks).map(t=>{const r=t.result||t.preview,d=r.verifiedDates;return [escape(t.orgUnitId),`<strong>${escape(t.name)}</strong><small>${escape(names[t.activity.type]||t.activity.type)} · ${escape(t.activity.id)}</small>`,badge(r.status),escape(date(d?.start,timeZone)),escape(date(d?.due,timeZone)),escape(date(d?.end,timeZone)),escape(r.error?.message||'—')];}),'Activities will appear after validation.')}</section><details class="technical"><summary>Job details</summary><p>Job ID: ${escape(job._id)}</p><p>Preview makes no changes. Apply uses only the activities in this saved plan. Each result is read back from Brightspace.</p></details>${navigation}`}${active?'<script>setTimeout(()=>document.getElementById("job-refresh").requestSubmit(),10000);</script>':''}`;
 }
};}
module.exports={createDateView};
