'use strict';
const {escape,badge,steps,table,upload,notice}=require('../ui/page');
function createDeploymentView({enabled}){return {
 canApply:()=>enabled(),
 form(res,{controls,button}){return `<section id="source-replication">${steps(['Upload mappings','Review & deploy','Confirm completion','Activate'])}<div class="section-heading"><div><h2>Deploy your Source Courses</h2><p>Copy a source into existing offerings, then activate them when copying is finished.</p></div><span class="badge neutral">Manual completion check</span></div><form method="post" action="/deploy/preview">${controls(res,'preview')}<div class="form-grid"><div class="panel">${upload('deploy','SourceOrgUnitId,ReplicaOrgUnitId','Provide both IDs on each row. Repeat a source ID to deploy it to several replicas.')}</div><aside class="panel guidance"><span class="eyebrow">Before you begin</span><h3>A fresh copy for every replica</h3><ol class="explanation"><li><strong>Prepare</strong><p>Replicas are made inactive before deployment.</p></li><li><strong>Deploy</strong><p>Brightspace resets replica content and copies the source.</p></li><li><strong>Activate later</strong><p>Check completion in Brightspace, then return here to activate every replica.</p></li></ol></aside></div><div class="action-bar"><p>Validation is read-only. You confirm before content is replaced.</p><button class="primary">Validate deployment mappings</button></div></form>${button(res,'history','','My deployment jobs')}</section>`;},
 render(res,job,{controls,button,now}){
 const active=['validating','planning','queued','running'].includes(job.status),activating=job.operation==='activate';
 const results=job.tasks.flatMap(t=>t.targets.map(target=>({sourceId:t.sourceId,sourceName:t.sourceName,target,...(t.result||t.preview),status:t.result?.targets?.find(r=>r.orgUnitId===target.orgUnitId)?.status||t.result?.status||'pending'})));
 const stage=job.status==='activated'||activating?3:['submitted','submittedWithErrors','outcomeUnknown'].includes(job.status)?2:job.status==='ready'||job.status==='running'||job.status==='queued'?1:0;
 const canActivate=['submitted','submittedWithErrors','outcomeUnknown','interrupted','failed','activationWithErrors'].includes(job.status)&&job.tasks.some(t=>t.targets.some(r=>r.deactivation));
 return `<div class="section-heading"><div><span class="eyebrow">Source replication</span><h1>${stage===0?'Check your course mappings':stage===1?'Review your deployment':stage===2?'Check copy completion':'Activate your replicas'}</h1></div>${badge(job.status)}</div>${steps(['Upload mappings','Review & deploy','Confirm completion','Activate'],stage)}<div class="metrics"><div><strong>${job.tasks.length}</strong><span>Sources</span></div><div><strong>${results.length}</strong><span>Replicas</span></div><div><strong>${results.filter(r=>['updated','unchanged'].includes(r.target.activation?.status)).length}</strong><span>Verified active</span></div></div>
 ${job.message?notice(job.message,['activated','submitted'].includes(job.status)?'default':'warning'):''}
 ${job.status==='ready'&&job.expiresAt>now()&&enabled()?`<section class="confirmation"><h2>Confirm replacement of replica content</h2><p>The app will deactivate the listed offerings, then ask Brightspace to replace their content from each source. They stay inactive until you return to activate them.</p><form method="post" action="/deploy/apply">${controls(res,'apply',job._id)}<label class="checkbox"><input type="checkbox" name="confirmReset" value="yes" required> I confirm Brightspace will reset all ${results.length} listed replicas and replace their content from the listed sources.</label><button class="primary">Prepare and deploy</button></form></section>`:''}
 ${job.status==='ready'&&!enabled()?notice('Deployment unavailable. Configure manageCourses:deploy:manage and orgunits:course:update (or matching wildcards), plus Service User permissions.','warning'):''}
 ${job.status==='ready'&&job.expiresAt<=now()?notice('Preview expired. Return to Workspace and validate your mappings again.','warning'):''}
 ${active?`<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>${job.status==='running'?(activating?'Activating and verifying replicas':'Preparing replicas and submitting deployment'):'Checking your mappings'}</strong><p>This page refreshes every 10 seconds. You can return through Job history.</p></div></div>`:''}
 ${canActivate?`<section class="confirmation"><h2>Copying finished in Brightspace?</h2><p>There is no automatic copy progress here. Check <strong>every replica</strong> in Brightspace and resolve failed or uncertain copies before continuing. All listed replicas will be activated, including those originally inactive.</p><form method="post" action="/deploy/activate">${controls(res,'activate',job._id)}<label class="checkbox"><input type="checkbox" name="confirmCompleted" value="yes" required> I have verified that all copies have finished, no deployment is still running, and every listed replica is ready to activate.</label><button class="primary">Activate replicas</button></form></section>`:''}
 <div class="toolbar">${button(res,'status',job._id,'Refresh submission status','id="deploy-refresh"')}${button(res,'report',job._id,'Download submission report')}${button(res,'history','','My deployment jobs')}${!activating&&['validating','ready','queued'].includes(job.status)?button(res,'cancel',job._id,'Cancel'):''}</div>
 <details class="panel" ${job.rows.some(r=>r.status==='invalid')?'open':''}><summary>CSV validation · ${job.rows.length} rows</summary>${table(['Row','Source ID','Replica ID','Status','Details'],job.rows.map(r=>[escape(r.row),escape(r.sourceId),escape(r.targetId),badge(r.status),escape(r.message||'—')]))}</details>
 <section class="panel"><h2>Sources and replicas</h2>${job.tasks.map(t=>`<div class="source-group"><h3>${escape(t.sourceName)} <small>Source ID ${escape(t.sourceId)}</small></h3>${table(['Replica','Initially active','Preparation','Deployment','Activation'],results.filter(r=>r.sourceId===t.sourceId).map(r=>[`<strong>${escape(r.target.name)}</strong><small>ID ${escape(r.target.orgUnitId)}</small>${r.target.activation?.error||r.target.deactivation?.error||r.error?`<p class="row-error">${escape(r.target.activation?.error?.message||r.target.deactivation?.error?.message||r.error?.message)}</p>`:''}`,r.target.isActive?'Yes':'No',r.target.deactivation?(['updated','unchanged'].includes(r.target.deactivation.status)?'<span class="badge success">Inactive · verified</span>':badge(r.target.deactivation.status)):'Not started',r.status==='ready'||r.status==='pending'?'Not submitted':badge(r.status),r.target.activation?(['updated','unchanged'].includes(r.target.activation.status)?'<span class="badge success">Active · verified</span>':badge(r.target.activation.status)):'Not activated']))}</div>`).join('')||'<p class="empty-state">Mappings will appear after validation.</p>'}</section>
 <details class="technical"><summary>Job details and deployment IDs</summary><p>Job ${escape(job._id)}</p><p>Submitted means accepted for processing, not verified completion.</p>${table(['Source ID','Deployment ID'],job.tasks.map(t=>[escape(t.sourceId),escape(t.result?.deploymentId||'Not submitted')]))}</details>${active?'<script>setTimeout(()=>document.getElementById("deploy-refresh").requestSubmit(),10000);</script>':''}`;
 },
  report(job){
   const rows=[['CSV row','Source ID','Replica ID','Source name','Replica name','Validation','Submission status','Deployment ID','Details','Deactivation','Activation']];
   for(const row of job.rows){const task=job.tasks.find(t=>t.sourceId===row.sourceId),r=task?.result;rows.push([row.row,row.sourceId,row.targetId,row.sourceName,row.targetName,row.status,r?.targets?.find(t=>t.orgUnitId===row.targetId)?.status||r?.status||'',r?.deploymentId,row.message||r?.error?.message,task?.targets.find(t=>t.orgUnitId===row.targetId)?.deactivation?.status,task?.targets.find(t=>t.orgUnitId===row.targetId)?.activation?.status]);}
   return '\uFEFF'+rows.map(row=>row.map(value=>{let v=String(value??'');if(/^\s*[=+\-@]|^[\t\r\n]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');
  }
 };
}
module.exports={createDeploymentView};
